version: '3.4'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: MsSqlServer2
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Thanh71311@
    ports:
     - "1434:1433"
    volumes:
     - ../mssql/db:/var/opt/mssql/data